config/routes.rb
Rails.application.routes.draw do

  root "home#home"

  get "/signin", to: "sessions#new", as: 'signin'
  post "/signin", to: "sessions#create"
  get "/signup", to: "users#new", as:'signup'
  
  get '/dumpsters', to: 'dumpsters#index'
  get '/dumpsters/new', to: 'dumpsters#new', as: 'new_dumpster'
  post '/dumpsters', to: 'dumpsters#create'


  resources :goods
  
  resources :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :dumpster
    belongs_to :user
end

app/models/dumpster.rb
class Dumpster < ApplicationRecord
    has_many :users, through: :comments
    has_many :comments
    has_many :goods

   

    def goods=(goods)
        goods.each do |product|
            if !product[:name].empty?
                if item = Goods.find_by(name: product[:name])
                    self.goods << new_item
                else
                    self.equipment.build(name: product[:name])
                end 
            end 
        end 
    end 
end

app/models/good.rb
class Good < ApplicationRecord
    belongs_to :dumpster 
    validates :name, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :dumpsters, through: :dumpsters
    has_many :goods, through: :dumpsters
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    helper_method :current_user
    
    
    private
    def verify_user_is_authenticated
      redirect_to '/' unless user_is_authenticated
    end

    def user_is_authenticated
      !!current_user
    end

    def current_user
      User.find_by(id:session[:user_id])
    end
    

end

app/controllers/dumpsters_controller.rb
class DumpstersController < ApplicationController
    #skip_before_action :verify_authenticity_token  

    def index 
        @dumpsters = Dumpster.all
    end 

    

    def show
        @dumpster = Dumpster.find(params[:id])
    end

    def new
        @dumpster = Dumpster.new
    end
    
    def create 
        
       @dumpster = Dumpster.new(dumpster_params)
       if @dumpster.save
        redirect_to dumpsters_path
       else
        render :new
       end 
    end 

    def edit
        @dumpster = Dumpster.find(params[:id])
    end 

    def update
        @dumpster = Dumpster.find(params[:id])
        
        @dumpster.update(dumpster_params)

        if @dumpster.save
            redirect_to dumpsters_path
        else 
            render :edit
        end 
    end 

    def destroy 
        @dumpster = Dumpster.find(params[:id])
        @dumpster.destroy
        flash[:notice] = "Dumpster Deleted."
        redirect_to dumpsters_path
    end 

    private

    def dumpster_params
        params.require(:dumpster).permit(:name, :address, :city, :state, :zipcode, goods: [:name])
    end 


end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
    
    
    def index 
    end 

    def new 
    end
     
    def create 
    end 

    def show 
    end

    def edit 
    end 

    def destroy
    end 


end

app/controllers/home_controller.rb
class HomeController < ApplicationController


    def home 
    end 
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    #skip_before_action :verify_user_is_authenticated, only: [:new,:create]

    def new
        @user = User.new
        @users = User.all
    end
       
    def create
        @user = User.find_by(name: params[:user][:name])
        if @user && @user.authenticate(params[:user][:password])
          session[:user_id] = @user.id
          
        else
            flash[:danger] = "invalid name/password combination"
          redirect_to signin_path
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_url
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    #before_action :verify_user_is_authenticated
    def new 
        @user = User.new
    end 

    def create 
        if (user = User.create user_params)
            session[:user_id] = user.id
            redirect_to user_path(user)
        else
            render 'new'
        end
    end 

    def show
        @user = User.find_by(id:params[:id])
    end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password_digest)
    end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dumpsters_helper.rb
module DumpstersHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dumpsters/_form.html.erb
<%=form_for (@dumpster) do |f|%>

        <div class="form-group">
                <%= f.label :name %><br>
                <%= f.text_field :name, class: "form-control" %></div>
    
        <div class="form-group">
                <%= f.label :address %><br>
                <%= f.text_field :address, class: "form-control" %></div>

        <div class="form-group">
                <%= f.label :city %><br>
                <%= f.text_field :city, class: "form-control" %></div>

        <div class="form-group">
                <%= f.label :state %><br>
                <%= f.text_field :state, class: "form-control" %></div>
    
        <div class="form-group">
                <%= f.label :zipcode %><br>
                <%= f.text_field :zipcode, class: "form-control" %></div>
        <%= f.submit %>


<%end%>

app/views/dumpsters/edit.html.erb
<h1>Editing Dumpster</h1>
 <%= render 'form' %>

app/views/dumpsters/index.html.erb
<div class="center">
      <%= link_to "Home", root_path, class: "btn btn-primary" %>
      <%= link_to "My Dumpsters"%>
       
    </div>



<h1>Dumpsters</h1>

<%= link_to "Create new Dumpster", new_dumpster_path %>

<%@dumpsters.each do |dumpster|%>
    <div>
        <h3><%= dumpster.name %></h3>
        <p><%= dumpster.address %></p>
        <p><%= dumpster.city %></p>
        <p><%= dumpster.state %></p>
        <p><%= dumpster.zipcode %></p>
        <% if dumpster.goods.count > 0%>
            <p>Types of Goods</p>
            <ul>
                <% dumpster.goods.each do |good|%>
                    <li><%= good.name %></li>
                <%end%>
            </ul>
        <%end%>
    </div>
<%end%>

app/views/dumpsters/new.html.erb
<h2>New Dumpster Form:</h2>

<%= render 'form' %>
<%= dumpsters_path %>

app/views/home/home.html.erb
<h1>Dumpster Diving</h1>
<div class= "dumpster-diving">
    <div class="center">
      <%= link_to "Sign In", signin_path, class: "btn btn-primary" %>
      <%= link_to "Sign Up", new_user_path, class: "btn btn-primary" %>
       
    </div>
    <div>
        <img src= "http://www.firstpresclarksville.org/wp-content/uploads/2018/02/Dumpster-Diving-And-Judgments.jpg" >  
    </div>
<p>If you are interested in being a part of the solution to food waste then this is the place for you. </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DumpsterDiving</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_for @user, url: dumpsters_path(@dumpster) do |f| %>
   <div class="form-group">
    <%= f.label :username %><br>
    <%= f.text_field :username, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :password, "Enter your password" %><br>
    <%= f.password_field :password, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :email, "Enter your email" %><br>
    <%= f.text_field :email, class: "form-control" %>
  </div>
   <div class="actions">
    <%= f.submit "Sign Up", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/signin.html.erb
<%= form_for @user, url: "/users/login" do |f| %>
   <div class="field"><%= f.label :name, "Select your name" %><br>
    <%= f.collection_select(:id, @users, :id, :name) %>
  </div>
   <div class="actions">
    <%= f.submit "Sign In"  %>
  </div>
<% end %> 